name: CI
on: [push, pull_request]

concurrency:
  group: ${{ github.head_ref || format('{0}-{1}', github.ref, github.run_number) }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
        platform: [bios, uefi]
        exclude:
          # FIXME: the build somehow ends up being corrupted with GCC's
          #        libexec/cc1 containing garbage data.
          - os: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/cache@v3.0.2
        with:
          path: "${{ github.workspace }}/toolchain/tools_${{ matrix.platform }}"
          key: "${{ runner.os }}-${{ runner.arch }}-${{ matrix.platform }}-gcc-toolchain"

      - name: Build platform toolchain & Hyper
        run: "${{ github.workspace }}/build.py ${{ matrix.platform }} --toolchain gcc --fetch-test-dependencies --no-tune-native"

      - name: Build test kernel
        run: ${{ github.workspace }}/tests/kernel/build.sh

      - name: Run tests
        run: python3 -m pytest ${{ github.workspace }}/tests/test_loader.py -rs -s -v --junitxml result.xml

      - name: Publish test results
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: result.xml
