# Do this because cmake attempts to link against -lc and crt0
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

if (HYPER_PLATFORM STREQUAL "uefi")
    set(HYPER_COMPILER_PREFIX x86_64-w64-mingw32)
else ()
    set(HYPER_COMPILER_PREFIX i686-elf)
endif ()

set(HYPER_TOOLCHAIN_ROOT ${CMAKE_CURRENT_LIST_DIR}/tools_${HYPER_PLATFORM})
set(HYPER_TOOLCHAIN_PATH ${HYPER_TOOLCHAIN_ROOT}/bin)
set(HYPER_TOOLCHAIN_PREFIX ${HYPER_TOOLCHAIN_PATH}/${HYPER_COMPILER_PREFIX}-)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR ${HYPER_ARCH})
set(CMAKE_SYSROOT "")

set(CMAKE_C_COMPILER ${HYPER_TOOLCHAIN_PREFIX}gcc)
set(CMAKE_LINKER ${HYPER_TOOLCHAIN_PREFIX}ld)

